### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by AlexisT37** [AlexisT37/Snowtricks#25]
Register page has a form with:
- username
- email address
- password

! WARNING If the full name of the author of a comment should be visible, then it should be present in the register page as well
- first name
- last name

**Comment by AlexisT37** [comment]
NO NEED FOR LAST NAME AND FIRST NAME JUST USE USERNAME, REGISTER SHOULD BE SIMPLE

**Comment by AlexMyddleware** [comment]
completed with the following commit
13db084143217cfe087c44a10f0f1c07b569a290
working mailer
