### ISSUE TITLE
Token after registering

### ISSUE THREAD

**Issue by AlexisT37** [AlexisT37/Snowtricks#26]
Once the form for register is filled and checked, the user should receive an email to validate account creation and activate the account (MEAN YOU SHOULD HAVE A VALIDATED FIELD IN YOUR DATABASE FOR ACCOUNT)
we will use a token, maybe jsonwebtoken

**Comment by AlexMyddleware** [comment]
made in 
5932eb912fd6ff6dcd3d8648bdb4df8edd8edc15
feat: add registration form
