### ISSUE TITLE
a list of tricks

### ISSUE THREAD

**Issue by AlexisT37** [AlexisT37/Snowtricks#3]
un annuaire des figures de snowboard. Vous pouvez vous inspirer de la [liste des figures](https://fr.wikipedia.org/wiki/Snowboard_freestyle#Les_types_de_tricks) sur Wikipédia.

**Comment by AlexMyddleware** [comment]
Completed in final version in
45cf35385c3daa2e2d4abb5b462cccc9b245823d
feat: homepage with tricks
